name: Deploy to Vertex AI Agent Engine

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/instabids-agents:${{ github.sha }}
        
    - name: Deploy to Vertex AI Agent Engine
      run: |
        gcloud beta agent-engine deployments create instabids-agents-deployment \
          --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/instabids-agents:${{ github.sha }} \
          --location=us-central1 \
          --enable-logging \
          --description="InstaBids Agents Deployment" \
          --endpoint-name=instabids-agents-endpoint \
          --project=${{ secrets.GCP_PROJECT_ID }}
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "Deployment successful! Access the endpoint at: https://us-central1-agent-engine.cloud.google.com/projects/${{ secrets.GCP_PROJECT_ID }}/endpoints/instabids-agents-endpoint"
        else
          echo "Deployment failed. Check logs for details."
        fi